const data = {
    products: [
      {
        _id: '1',
        name: 'Almaz',
        category: 'SUV',
        image: '/images/almaz.jpg',
        price: 349000000,
        countInStock: 10,
        brand: 'Wuling',
        rating: 4.5,
        numReviews: 10,
        description: 'mobil bekas',
      },
      {
        _id: '2',
        name: 'E40',
        category: 'Sedan',
        image: '/images/e40.jpg',
        price: 769000000,
        countInStock: 0,
        brand: 'BMW',
        rating: 4.0,
        numReviews: 10,
        description: 'mobil bekas',
      },
      {
        _id: '3',
        name: 'M3 GTR',
        category: 'Coupe',
        image: '/images/m3.jpg',
        countInStock: 20,
        price: 564300000,
        brand: 'BMW',
        rating: 4.5,
        numReviews: 4,
        description: 'mobil bekas',
      },
      {
        _id: '4',
        name: 'Pajero Sports',
        category: 'SUV',
        image: '/images/pajero.jpg',
        price: 440000000,
        countInStock: 9,
        brand: 'Mitsubishi',
        rating: 4.5,
        numReviews: 10,
        description: 'mobil bekas',
      },
      {
        _id: '5',
        name: 'Supra',
        category: 'Sport',
        image: '/images/supra.jpg',
        price: 1300000000,
        countInStock: 30,
        brand: 'Toyota',
        rating: 4.5,
        numReviews: 10,
        description: 'mobil bekas',
      },
      {
        _id: '6',
        name: 'Xpander Cross',
        category: 'SUV',
        image: '/images/xpander.jpg',
        price: 139000000,
        countInStock: 45,
        brand: 'Mitsubishi',
        rating: 4.5,
        numReviews: 15,
        description: 'mobil bekas',
      },
    ],
  };
  export default data;